---
galaxy_info:
  author: sfuhrm
  company: sfuhrm
  description: AdoptOpenJDK Java role
  min_ansible_version: 2.4
  license: Apache 2.0
  galaxy_tags:
    - development
    - java
    - jdk
    - openjdk
    - adoptopenjdk
  platforms:
  - name: Fedora
    versions:
      - all
  - name: Ubuntu
    versions:
      - all
  - name: Debian
    versions:
      - all
