# To install the roles, run

- name: Reinstall GNOME settings
  hosts: localhost
  become: yes
  become_user: aaron
  vars_files:
    - global-vars.yaml
  tasks:
    - name: Night mode auto
      dconf:
        key: /org/gnome/settings-daemon/plugins/color/night-light-schedule-automatic
        value: 'false'

    - name: Night mode from
      dconf:
        key: /org/gnome/settings-daemon/plugins/color/night-light-schedule-from
        value: '3.0'

    - name: Night mode to
      dconf:
        key: /org/gnome/settings-daemon/plugins/color/night-light-schedule-to
        value: '3.0'

    - name: Night mode temp
      dconf:
        key: /org/gnome/settings-daemon/plugins/color/night-light-temperature
        value: 'uint32 2700'

    - name: Night mode enabled
      dconf:
        key: /org/gnome/settings-daemon/plugins/color/night-light-enabled
        value: 'true'

    - name: Flameshot keybinding name
      dconf:
        key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/name
        value: "'Flameshot'"

    - name: Flameshot command
      dconf:
        key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/command
        value: "'flameshot gui'"

    - name: Flameshot bind to a key combo
      dconf:
        key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/binding
        value: "'Print'"

    - name: Ext
      dconf:
        key: /org/gnome/shell/enabled-extensions
        value: "['clipboard-indicator@tudmotu.com', 'cpupower@mko-sl.de']"

    - name: Mouse natural
      dconf:
        key: /org/gnome/desktop/peripherals/mouse/natural-scroll
        value: 'true'

    - name: Touchpad natural
      dconf:
        key: /org/gnome/desktop/peripherals/touchpad/natural-scroll
        value: 'true'

    - name: Wallpaper
      dconf:
        key: /org/gnome/desktop/background/picture-uri
        value: "'file:///home/aaron/Pictures/coral.jpg'"

    - name: IM Module
      dconf:
        key: /org/gnome/desktop/interface/gtk-im-module
        value: "'gtk-im-context-simple'"

    - name: Theme
      dconf:
        key: /org/gnome/desktop/interface/gtk-theme
        value: "'Orchis-light'"

    - name: Favorites icons
      dconf:
        key: /org/gnome/shell/favorite-apps
        value: "['org.gnome.Nautilus.desktop', 'jetbrains-idea-ce.desktop', 'google-chrome.desktop', 'slack_slack.desktop', 'org.gnome.Terminal.desktop', 'gnome-control-center.desktop', 'firefox.desktop', 'notepadqq.desktop']"
