- name: Root tasks
  hosts: localhost
  connection: local
  become: yes
  vars_files:
    - global-vars.yaml
  tasks:
    - name: Upgrade all apt packages
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
      
    - name: Add the flathub flatpak repository remote to the user installation
      community.general.flatpak_remote:
        name: flathub
        flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
        
    - name: Install Debian packages
      apt:
        name:
          - ansible-lint
          - arandr
          - baobab
          - build-essential
          - cmake
          - cmake-curses-gui
          - curl
          - default-jdk
          - openjdk-11-source
          - openjdk-11-dbg
          - fd-find
          - flameshot
          - flatpak
          - git
          - golang-go
          - gnupg
          - gnome-tweaks
          - graphviz
          - htop
          - intel-media-va-driver-non-free
          - iotop
          - kylin-video
          - libjsoncpp-dev
          - libqpid-proton11
          - libssl-dev
          - libtool
          - libva-drm2
          - libva-x11-2
          - locate
          - make
          - maven
          - mesa-va-drivers
          - notepadqq
          - p7zip-full
          - p7zip-rar
          - pkg-config
          - python3-dev
          - python3-pip
          - qbittorrent
          - redshift-gtk
          - rpm
          - ruby-full
          - software-properties-common
          - sysstat
          - swig
          - transmission-cli
          - uuid-dev
          - vim
          - vagrant
#          - virtualbox
#          - virtualbox-ext-pack
        state: present

    - name: PKCS 11 libs
      apt:
        name:
          - libpcsclite1
          - pcscd
          - pcsc-tools
          - opensc
          - libnss3-tools
        state: present

#    - name: Install Snaps
#      community.general.flatpak:
#        name:
#          - obs-studio
#          - vlc
#          - aws-cli


#    - name: Install OBS add-ons
#      shell: |
#        snap connect obs-studio:alsa \
#        && snap connect obs-studio:audio-record \
#        && snap connect obs-studio:avahi-control \
#        && snap connect obs-studio:camera \
#        && snap connect obs-studio:jack1 \
#        && snap connect obs-studio:removable-media \


      # psutil upgrade was needed for Ubuntu 20.04
    - name: Update pip
      command: pip3 install --upgrade psutil

    - name: Snaps
      snap:
        name:
          - slack
          - gimp

    - name: Create projects dir
      file:
        path: /projects
        state: directory
        mode: '0755'
        owner: aaron
        group: aaron

    - name: Create builds dir
      file:
        path: /builds
        state: directory
        mode: '0755'
        owner: aaron
        group: aaron

    - name: Add global aliaeses
      blockinfile:
        path: /etc/bash.bashrc
        block: |
          alias ll='ls -alh'
          alias fd='fdfind -H'

    - name: Make sure enough files can be created
      lineinfile:
        path: /etc/sysctl.conf
        line: 'fs.inotify.max_user_watches = 524288'

# Install signal
- hosts: localhost
  roles:
    - role: staticdev.signal
