- name: Root tasks
  hosts: localhost
  connection: local
  become: yes
  vars_files:
    - vars.yaml

  tasks:
    - name: Update apt cache
      apt: update_cache=yes

    - name: Upgrade all apt packages
      apt: upgrade=dist

    - name: Install Debian packages
      apt:
        name:
          - ansible-lint
          - clipit
          - baobab
          - flameshot
          - git
          - gnome-tweaks
          - locate
          - maven
          - python3-pip
          - vim
        state: present

    - name: PKCS 11 libs
      apt:
        name:
          - libpcsclite1
          - pcscd
          - pcsc-tools
          - opensc
          - libnss3-tools
        state: present

    # psutil upgrade was needed for Ubuntu 20.04
    - name: Update pip
      command: pip3 install --upgrade psutil

    - name: Slack
      snap:
        name:
          - slack
          - gimp
        classic: yes

    - name: Create projects dir
      file:
        path: /projects
        state: directory
        mode: '0755'
        owner: aaron
        group: aaron

    - name: Create builds dir
      file:
        path: /builds
        state: directory
        mode: '0755'
        owner: aaron
        group: aaron
