- name: Root tasks
  hosts: localhost
  connection: local
  become: yes
  vars_files:
    - global-vars.yaml

  tasks:
    - name: Accept virtualbox-ext-pack seen license
      debconf:
        name: virtualbox-ext-pack
        question: virtualbox-ext-pack/license
        value: 'true'
        vtype: seen

    - name: Accept virtualbox-ext-pack select license
      debconf:
        name: virtualbox-ext-pack
        question: virtualbox-ext-pack/license
        value: 'true'
        vtype: select

    - name: Add an hashicorps key by id
      ansible.builtin.apt_key:
        keyserver: https://apt.releases.hashicorp.com/gpg
        id: E8A032E094D8EB4EA189D270DA418C88A3219F7B

    - name: Add Hashicorp's vagrant repo into sources list
      apt_repository:
        repo: deb [arch=amd64] https://apt.releases.hashicorp.com focal main
        state: present

    - name: Add ppa for Terminator
      apt_repository:
        repo: deb http://ppa.launchpad.net/mattrose/terminator/ubuntu focal main
        state: present

    - name: Upgrade all apt packages
      apt:
        upgrade: dist
        update_cache: yes

    - name: Install Debian packages
      apt:
        name:
          - ansible-lint
          - arandr
          - build-essential
          - cmake
          - cmake-curses-gui
          - baobab
          - default-jdk
          - fd-find
          - flameshot
          - git
          - gnome-tweaks
          - htop
          - iotop
          - golang-go
          - libjsoncpp-dev
          - libqpid-proton11
          - libssl-dev
          - libtool
          - locate
          - make
          - maven
          - notepadqq
          - p7zip-full
          - p7zip-rar
          - pkg-config
          - python3-dev
          - python3-pip
          - qbittorrent
          - rpm
          - ruby-full
          - sysstat
          - swig
          - terminator
          - transmission-cli
          - uuid-dev
          - vim
          - vagrant
          - virtualbox
          - virtualbox-ext-pack
          - vlc
          - intel-media-va-driver-non-free
          - libva-drm2
          - libva-x11-2
          - mesa-va-drivers
        state: present

    - name: PKCS 11 libs
      apt:
        name:
          - libpcsclite1
          - pcscd
          - pcsc-tools
          - opensc
          - libnss3-tools
        state: present

    # psutil upgrade was needed for Ubuntu 20.04
    - name: Update pip
      command: pip3 install --upgrade psutil

    - name: Slack
      snap:
        name:
          - slack
          - gimp
        classic: yes

    - name: Create projects dir
      file:
        path: /projects
        state: directory
        mode: '0755'
        owner: aaron
        group: aaron

    - name: Create builds dir
      file:
        path: /builds
        state: directory
        mode: '0755'
        owner: aaron
        group: aaron

    - name: Add global aliaeses
      blockinfile:
        path: /etc/bash.bashrc
        block: |
          alias ll='ls -alh'
          alias fd='fdfind -H'