---

- name: Add the Apt signing key of AdoptOpenJDK from jfrog.io
  apt_key:
    url: https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public
    state: "{{ adoptopenjdk_state }}"

- name: Add apt repository for AdoptOpenJDK
  apt_repository:
    repo: "deb https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/ {{ ansible_distribution_release }} main"
    filename: adoptopenjdk_role
    state: "{{ adoptopenjdk_state }}"

- name: Install AdoptOpenJDK package
  apt:
    name: "{{ adoptopenjdk_package }}"
    state: "{{ adoptopenjdk_state }}"
    update_cache: yes
