---
- name: Find out OS release
  shell: . /etc/os-release  && echo $ID
  register: osrelease

- name: Add yum repository for AdoptOpenJDK
  yum_repository:
    baseurl: "http://adoptopenjdk.jfrog.io/adoptopenjdk/rpm/{{ osrelease.stdout }}/$releasever/$basearch"
    enabled: yes
    gpgcheck: yes
    gpgkey: https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public
    name: adoptopenjdk_role
    description: AdoptOpenJDK Java packages
    state: "{{ adoptopenjdk_state }}"

- name: Install AdoptOpenJDK package
  yum:
    name: "{{ adoptopenjdk_package }}"
    state: "{{ adoptopenjdk_state }}"
    update_cache: yes
